# Properties
mod_id=hoarding
mod_name=Hoarding
mod_license=MIT
mod_group_id=dev.gateguardian
mod_authors=sagesse
mod_description=Hoarding mod for Minecraft

# Minecraft & NeoForge
minecraft_version_range=[1.21.1,1.22)
neo_version_range=[21.1.218,21.2.0)
loader_version_range=[4,5)

# Gradle
org.gradle.jvmargs=-Xmx3G -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djavax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# 网络超时配置
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000

# 代理配置 (HTTP/HTTPS)
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897

# 跳过本地地址代理
systemProp.http.nonProxyHosts=localhost|127.0.0.1
